#cloud-config
# =============================================================================
# Sales Platform — Cloud-Init (full first-boot automation)
# Generated by Terraform. Runs once on VM creation.
# =============================================================================

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - git
  - ufw
  - fail2ban
  - htop
  - jq
  - python3-minimal
  - unzip
  - make

write_files:
  # --- Application environment ---
  - path: /opt/sales-platform/.env
    permissions: '0600'
    owner: root:root
    content: |
      DATABASE_URL=postgresql+asyncpg://postgres:${postgres_password}@postgres:5432/jobplatform
      DATABASE_URL_SYNC=postgresql://postgres:${postgres_password}@postgres:5432/jobplatform
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=${postgres_password}
      POSTGRES_DB=jobplatform
      POSTGRES_HOST=postgres
      POSTGRES_PORT=5432
      REDIS_URL=redis://redis:6379/0
      APP_URL=https://${app_domain}
      API_URL=https://${app_domain}/api
      JWT_SECRET=${jwt_secret}
      JWT_EXPIRE_HOURS=24
      ANTHROPIC_API_KEY=${anthropic_api_key}
      SCAN_MODE=normal
      SCAN_INTERVAL_HOURS=6
      CAREER_PAGE_INTERVAL_HOURS=4
      BACKUP_DIR=/app/backups
      BACKUP_KEEP_LAST=14
      CELERY_CONCURRENCY=2

  # --- CPU keepalive script (prevents Oracle free-tier reclaim) ---
  - path: /opt/sales-platform/infra/scripts/keepalive.sh
    permissions: '0755'
    owner: root:root
    content: |
      #!/bin/bash
      # Oracle reclaims free-tier instances with <10% CPU over 7 days.
      # This generates a 2-minute CPU burst every 6 hours to stay above threshold.
      logger "keepalive: starting CPU burst"
      timeout 120 sh -c 'while true; do echo "keepalive" | md5sum > /dev/null; done' 2>/dev/null
      logger "keepalive: burst completed"

  # --- Cloudflared systemd service ---
  - path: /etc/systemd/system/cloudflared-tunnel.service
    permissions: '0644'
    owner: root:root
    content: |
      [Unit]
      Description=Cloudflare Tunnel for ${instance_name}
      After=docker.service network-online.target
      Wants=network-online.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/cloudflared tunnel --no-autoupdate run --token ${tunnel_token}
      Restart=always
      RestartSec=5
      User=root

      [Install]
      WantedBy=multi-user.target

runcmd:
  - echo "=== CLOUD-INIT START $(date -u) ===" >> /var/log/cloud-init-status.log

  # 1. Install Docker
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update -qq
  - apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - systemctl enable docker && systemctl start docker
  - usermod -aG docker ubuntu
  - echo "DOCKER_INSTALLED=$(date -u)" >> /var/log/cloud-init-status.log

  # 2. Install cloudflared
  - curl -sSL -o /usr/local/bin/cloudflared "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-$(dpkg --print-architecture)"
  - chmod +x /usr/local/bin/cloudflared
  - echo "CLOUDFLARED_INSTALLED=$(date -u)" >> /var/log/cloud-init-status.log

  # 3. Firewall (SSH only — tunnel handles web traffic)
  - ufw --force reset
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp
  - ufw --force enable

  # 4. Fail2ban
  - systemctl enable fail2ban && systemctl start fail2ban

  # 5. Swap (2GB safety net)
  - |
    if [ ! -f /swapfile ]; then
      fallocate -l 2G /swapfile
      chmod 600 /swapfile
      mkswap /swapfile && swapon /swapfile
      echo '/swapfile none swap sw 0 0' >> /etc/fstab
      sysctl -w vm.swappiness=10
      echo "vm.swappiness=10" >> /etc/sysctl.conf
    fi

  # 6. Install GitHub deploy key + clone repo
  - |
    # Install the ED25519 deploy key generated by Terraform (read-only access to the repo).
    # The private key was base64-encoded in the Terraform template to survive YAML escaping.
    mkdir -p /root/.ssh
    chmod 700 /root/.ssh
    echo "${github_deploy_key_b64}" | base64 -d > /root/.ssh/id_ed25519
    chmod 600 /root/.ssh/id_ed25519
    # Add GitHub to known_hosts so git clone doesn't prompt for host verification.
    ssh-keyscan -H github.com >> /root/.ssh/known_hosts 2>/dev/null
    chmod 644 /root/.ssh/known_hosts
    echo "DEPLOY_KEY_INSTALLED=$(date -u)" >> /var/log/cloud-init-status.log
  - |
    if [ -n "${git_repo_url}" ]; then
      # Use the deploy key for SSH clones (git@github.com:...) or fall through for public HTTPS.
      GIT_SSH_COMMAND="ssh -i /root/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
        git clone "${git_repo_url}" /tmp/sales-repo 2>&1 || true
      if [ -d /tmp/sales-repo/platform ]; then
        cp -r /tmp/sales-repo/platform/* /opt/sales-platform/
      elif [ -d /tmp/sales-repo ]; then
        cp -r /tmp/sales-repo/* /opt/sales-platform/
      fi
      rm -rf /tmp/sales-repo
    fi
  - echo "REPO_CLONED=$(date -u)" >> /var/log/cloud-init-status.log

  # 7. Build Docker images
  - |
    cd /opt/sales-platform
    if [ -f Makefile ]; then
      make build 2>&1 | tee /var/log/sales-platform-build.log
    elif [ -f docker-compose.prod.yml ]; then
      docker compose -f docker-compose.prod.yml build 2>&1 | tee /var/log/sales-platform-build.log
    fi
  - echo "IMAGES_BUILT=$(date -u)" >> /var/log/cloud-init-status.log

  # 8. Start Cloudflare Tunnel
  - systemctl daemon-reload
  - systemctl enable cloudflared-tunnel
  - systemctl start cloudflared-tunnel
  - echo "TUNNEL_STARTED=$(date -u)" >> /var/log/cloud-init-status.log

  # 9. Start application stack
  - |
    cd /opt/sales-platform
    docker compose -f docker-compose.prod.yml up -d 2>&1 | tee /var/log/sales-platform-deploy.log
  - echo "APP_STARTED=$(date -u)" >> /var/log/cloud-init-status.log

  # 10. Wait for Postgres, then migrate and seed
  - sleep 30
  - |
    cd /opt/sales-platform
    docker compose -f docker-compose.prod.yml run --rm backend alembic upgrade head 2>&1 || true
    docker compose -f docker-compose.prod.yml exec -T backend python -m app.seed_admin 2>&1 || true
    docker compose -f docker-compose.prod.yml exec -T backend python -m app.seed_remote_companies 2>&1 || true
  - echo "DB_MIGRATED=$(date -u)" >> /var/log/cloud-init-status.log

  # 11. Setup cron jobs
  - |
    # CPU keepalive (every 6 hours — prevents Oracle free-tier reclaim)
    echo "0 */6 * * * /opt/sales-platform/infra/scripts/keepalive.sh >> /var/log/keepalive.log 2>&1" | crontab -u root -
    # Nightly database backup (3 AM)
    (crontab -u root -l 2>/dev/null; echo "0 3 * * * cd /opt/sales-platform && bash infra/scripts/backup.sh >> /opt/sales-platform/backups/cron.log 2>&1") | crontab -u root -

  - echo "=== CLOUD-INIT COMPLETE $(date -u) ===" >> /var/log/cloud-init-status.log

final_message: "Sales Platform bootstrap complete after $UPTIME seconds"
